### ISSUE TITLE
[Feature Request] Diversified Citation key 

### ISSUE THREAD

**Issue by panwanke** [sophosia/sophosia-releases#55]
This is a great project that promises to replace the inefficient zotero. 

I notice that the citation key can now only set **authors, title, and year**. And these three keywords are required, which means that the combination of title+year is not allowed. 

It is nessary to allow these setting first I thought. 
Secondly, I think it is also possible to add other keywords such as **journal abbreviation**. For example, I am used to combining author+year+jouranlabbreviation as citationkey. 

Finally, feel the developer's effort again.

**Comment by HuntFeng** [comment]
Thanks for the support! Yes, the ability to freely set citation key is a feature I want as well.
